project_name: 'urban-incivility-enriched'
dataset_path: './data/tiny/tiny_enriched_prompt.jsonl'
np: 2
export_path: './outputs/urban-incivility/enriched.jsonl'

text_keys: 'text'
image_key: 'images'

process:
  - mllm_mapper:
      hf_model: 'Qwen/Qwen2-VL-7B-Instruct'
      max_new_tokens: 256
      temperature: 0.3
      accelerator: 'cuda'
      memory: '22GB'
